version: "3"
services:
  httpbin:
    image: "kennethreitz/httpbin"
    ports:
      - "80:80"

  kong-dashboard:
    image: "pgbi/kong-dashboard"
    ports:
      - "8080:8080"
    command: ["start", "--kong-url", "http://kong:8001"]
    restart: always
    depends_on:
      - "kong"

  postgres:
    image: "postgres:9.5"
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"

  kong:
    build: "."
    environment:
      - "KONG_PG_HOST=postgres"
      - "KONG_PG_DATABASE=kong"
      - "KONG_PG_USER=kong"
      - "KONG_PG_PASSWORD=password"
      - "KONG_PROXY_LISTEN=0.0.0.0:80"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
      - "KONG_LUA_PACKAGE_PATH=/opt/babylon/?.lua;;"
    ports:
      - "8443:443"
      - "8000:80"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - "postgres"
    restart: always